services:
  # Database service for the application
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: ElasticSearch
    networks:
      - elastic-jaeger
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    restart: on-failure
    environment:
      - cluster.name=jaeger-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  # Jaeger Collector service
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.42
    container_name: JaegerCollector
    networks:
      - elastic-jaeger
    ports:
      - "14250:14250"
      - "14267:14267"
      - "4318:4318"
      - "14269:14269"
    restart: on-failure
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      COLLECTOR_OTLP_ENABLED: "true"
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--log-level=error"
    ]
    depends_on:
      - elasticsearch

  # Jaeger Agent service
  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.42
    container_name: JaegerAgent
    networks:
      - elastic-jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
    command: [
      "--reporter.grpc.host-port=jaeger-collector:14250"
    ]
    restart: on-failure
    depends_on:
      - jaeger-collector

  # Jaeger Query service
  jaeger-query:
    image: jaegertracing/jaeger-query:1.42
    container_name: JaegerQuery
    networks:
      - elastic-jaeger
    ports:
      - 16686:16686
      - "16687:16687"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - no_proxy=localhost
    restart: on-failure
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--span-storage.type=elasticsearch",
      "--log-level=debug"
    ]
    depends_on:
      - jaeger-agent

volumes:
  esdata:
    driver: local

networks:
  elastic-jaeger:
    driver: bridge
